language: java
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/bwehrle/vlingo-actors.git
- cd vlingo-commons && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: bwehrle
  on:
    branch: master
  key:
    secure: 
  passphrase:
    secure: 
notifications:
  email:
    - bwolesa@gmail.com
